### ISSUE TITLE
Docker module

### ISSUE THREAD

**Issue by ozbillwang** [galal-hussein/Rancher-Ansible#1]
@galal-hussein 

This is nice job you did. Could you please confirm where you input the docker module, or you made it by yourself?

Seems your codes only work for `Ubuntu 14.04`

https://github.com/galal-hussein/Rancher-Ansible/blob/master/roles/docker/tasks/main.yml#L2

So why not use the exist ansible docker directly?

http://docs.ansible.com/ansible/docker_module.html

**Comment by galal-hussein** [comment]
I made the docker role, and also i use the existing docker module but the Ansible role i created its goal to only install docker on the host it has nothing to do with the Ansible's docker module.

And the role unfortunately works only on Ubuntu but I will work on getting other distros work too.

**Comment by ozbillwang** [comment]
Thanks for the updates. Let me see if I can involve.
