### ISSUE TITLE
Re-organise this repo

### ISSUE THREAD

**Issue by ozbillwang** [galal-hussein/Rancher-Ansible#2]
When go through the recommend ansible repo in Rancher README (https://github.com/joshuacox/ansibleplaybook-rancher), I like yours more. 

But there are some other modules included which I don't think it is a good idea. 

Let's focus it on Rancher Ansible playbook only. 
-  Docker installation.

It should assume that Docker has been installed, it can be prepared by seperate Docker ansible playbook, or installed into base IMAGE directly (such as via packer).

The only thing Rancher ansible need check is, Docker version must be newer than v1.9.1+
- wordpress and mysql module. 

I understand you use them as a sample for others, but I hope it can be removed out of the repo. Or you can move it to test sub-folder as sample.

Since we have Rancher server/hosts running, we can create mysql and wordpress container in Rancher directly. 

And if you'd like to show us the sample, it will be better to do it via api in rancher.
- Initialize users/groups

add features to set a local admin account and generate an API key/pass to make the playbook work in  production environment.

Can add new feature to integrate with ldap or active directory later.

**Comment by SydOps** [comment]
Ok, I see the declaim that you can comment the docker and wordpress parts if not required.

**Comment by galal-hussein** [comment]
@SydOps I think you are absolutely right, the repo should only focus on Rancher installation and configuration, I am planning to work on these enhancements, especially for initializing admin local account.
