### ISSUE TITLE
repo description

### ISSUE THREAD

**Issue by mkozjak** [galal-hussein/Rancher-Ansible#3]
You have "Using Ansible to to run Rancher platform and register hosts" instead of "Using Ansible to run Rancher platform and register hosts" in repo description...

**Comment by ozbillwang** [comment]
so, why not raise PR directly to fix it?

**Comment by galal-hussein** [comment]
Fixed.. @mkozjak @ozbillwang Thanks

**Comment by mkozjak** [comment]
@ozbillwang Go ahead and think again. ;)
